// Enum con tutti i tipi di risposta di successo
export enum SuccessEnum {
  UserRegistered     = 'UserRegistered',
  UserLoggedIn       = 'UserLoggedIn',
  UsersFetched       = 'UsersFetched',
  UserFetched        = 'UserFetched',
  UserCreated        = 'UserCreated',
  UserUpdated        = 'UserUpdated',
  UserDeleted        = 'UserDeleted',
  DocumentsFetched   = 'DocumentsFetched',
  DocumentFetched    = 'DocumentFetched',
  DocumentCreated    = 'DocumentCreated',
  DocumentUpdated    = 'DocumentUpdated',
  DocumentDeleted    = 'DocumentDeleted',
  DocumentAnalyzed   = 'DocumentAnalyzed',
  AnonymizationPreviewed = 'AnonymizationPreviewed',
  RegulationsFetched = 'RegulationsFetched',
  RegulationFetched  = 'RegulationFetched',
  RegulationCreated  = 'RegulationCreated',
  RegulationUpdated  = 'RegulationUpdated',
  RegulationDeleted  = 'RegulationDeleted',
  AnalysesFetched    = 'AnalysesFetched',
  AnalysisFetched    = 'AnalysisFetched',
  TokensFetched      = 'TokensFetched',
  ProfileFetched     = 'ProfileFetched',
  ProfileUpdated     = 'ProfileUpdated',
  TokensRecharged    = 'TokensRecharged',
}